### ISSUE TITLE
Unable to install and use the converter

### ISSUE THREAD

**Issue by drorata** [eggcaker/jekyll-org#11]
I started a fresh Jekyll website and tried to include the `jekyll-org` converter. However, I fail to install it....

I don't understand the second part of the instructions. Should I do both? I only added the submodule, but then `jeykll serve` yields something like: `Build Warning: Layout 'posts' requested in _posts/2015-05-29-test.org does not exist.` when I try to add a new post. The post is found and added but without a title, tags etc. 

Can someone help me with the setting phase?

**Comment by drorata** [comment]
It seems like I managed to solve it. I had to save the converter in `_plugins` and not in a subdirectory. Is it possible?

I have one more question: is this convertor only useful for posts? I didn't manage to use it for a page...

**Comment by eggcaker** [comment]
@drorata you are right ,you should create `_plugins` directory then copy or clone the converter into it . 
for page convert , not support so far.

**Comment by drorata** [comment]
Indeed seems to work fine. Adding support for the pages would be really nice. What does it take to implement this?

**Comment by eggcaker** [comment]
i'll implement this when i have some free time. :(

**Comment by drorata** [comment]
I would be happy to help!

**Comment by eggcaker** [comment]
cool, PR are welcome !
