### ISSUE TITLE
Please release this plugin as a gem!

### ISSUE THREAD

**Issue by stig** [eggcaker/jekyll-org#19]
I would like to add this plugin to GitHub Pages' [plugin whitelist](https://github.com/github/pages-gem/blob/master/lib/github-pages/configuration.rb#L15), so jekyll-org can be used with vanilla GitHub Pages. But as far as I can see whitelisted plugins needs to be installable as gems. Could you please consider this?

**Comment by eggcaker** [comment]
wow, sounds cool!  I'll  look at how to make gem.

**Comment by stig** [comment]
Don't get too excited: I don't know if they will accept it! There's a chance though, since they already support the org-ruby gem for their READMEs.

**Comment by stig** [comment]
Any progress on this?

**Comment by eggcaker** [comment]
Published! 
https://rubygems.org/gems/jekyll-org

**Comment by stig** [comment]
Excellent! I'll test it and raise a PR to include it in the github-pages gem, although whether they'll actually accept it is not up to me though. Thanks for your work!

**Comment by stig** [comment]
Raised here: https://github.com/github/pages-gem/pull/335

**Comment by eggcaker** [comment]
cool!
