### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by flowsta** [eggcaker/jekyll-org#26]
Have you tried to insert an image?

If you have something like this:
```
#+CAPTION: Caption
#+ATTR_HTML: :alt alt attribute :title title attribute
http://url-image.jpg
```

The HTML is:

```
<p>http://url-image.jpg</p>
```

And there is not an image displayed but text.

Have I missed something to make it work?

Best!

**Comment by kevzettler** [comment]
you can render the image like:

`[[http://url-image.jpg]]`

I don't believe the `#+ATTR_HTML:` works though

maybe @eggcaker can confirm

**Comment by eggcaker** [comment]
normal i using the [[image url ]] syntax to insert image
