### ISSUE TITLE
Date insertion

### ISSUE THREAD

**Issue by flowsta** [eggcaker/jekyll-org#27]
Hi

According to org-mode, you can insert a date with the LaTeX header:

```
#+DATE: <2017-12-01 vie>
```

But Jekyll says:

> Error: undefined method `strftime' for "<2017-12-01 vie>":String Did you mean? strip

Is it possible to use the `DATE` tag? If not, what is the way to do it properly?

Best!

**Comment by eggcaker** [comment]
seems working now with latest version of jekyll-org.
