### ISSUE TITLE
How to deploy to github pages?

### ISSUE THREAD

**Issue by kevzettler** [eggcaker/jekyll-org#30]
Apparently, github pages executes `jekyll build` with the `--safe` option ignoring plugins.
see: https://jekyllrb.com/docs/plugins/

And only supports a limited set of plugins: https://pages.github.com/versions/

You can do a static build beforehand and commit the build. Kind of a pain.

@eggcaker what are you using for static hosting?

**Comment by eggcaker** [comment]
I generate all contents locally and run some simple shell script to build && upload all generated files to github pages, always use gihhubpages as a STATIC hosting.
