### ISSUE TITLE
Parse src-block results?

### ISSUE THREAD

**Issue by Qquanwei** [eggcaker/jekyll-org#31]
Current the src result block is hidden,  it would be helpful when can display.

**Comment by Wheest** [comment]
This setting can be configured using org-babel header arguments ([see its excellent README](https://org-babel.readthedocs.io/en/latest/header-args/#results)).
But the tl;dr of it is that for some src block, for example 
```
#+BEGIN_SRC python :results output :session qc0
print("awright, world")
#+END_SRC

#+RESULTS:
: awright, world
```

Can have the header argument `:exports both` set, which will export both the code block and the result.  

If you want the results inserted as another code block, adding `code` to your `:results` output should do it.  However there are loads of settings in there that will allow you to configure how you want

```
#+BEGIN_SRC python :results code output :session qc0 :exports both
print("awright, world!")
#+END_SRC

#+RESULTS:
#+BEGIN_SRC python
awright, world!
#+END_SRC
```

**Comment by oystersauce8** [comment]
hi @Wheest curious, what the url of your jekyll blog?  I'm looking for theming inspiration.

**Comment by Wheest** [comment]
Hi there @oystersauce8, you'll find it at [gibsonic.org](gibsonic.org).  Only one published post, since most of my stuff lives in drafting hell forever :).  In terms of theme, I've just stuck with Minima, it's clean, and doesn't get in the way

**Comment by Wheest** [comment]
Not to turn this GH issue into a watercooler thread, but hadn't heard up Upwork before.  Sounds like an interesting way to do freelance
