### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by oystersauce8** [eggcaker/jekyll-org#36]
I'm a bit confused about three similarly named/topic projects.

```
  https://github.com/eggcaker/jekyll-org
  https://github.com/bmaland/happyblogger
  https://github.com/ardumont/org2jekyll
```

It would helpful if the README included links to them, and also where this project fits in the bigger scheme of things.

**Comment by xyyuchn** [comment]
Hi oystersauce8,
Maybe it is too late, you can see [org2jekyll](https://github.com/ardumont/org2jekyll#description)'s descriptions for comparison.
