### ISSUE TITLE
Parse LaTeX source blocks

### ISSUE THREAD

**Issue by Wheest** [eggcaker/jekyll-org#38]
For LaTeX equations, one can surround the snippet in double `$`, or `\(` `\)` and jekyll-org will export it fine.

For example:
```
$$A[v_1, v_2, \ldots, v_r] = [\sigma_1 u_1, \sigma_2 u_2, \ldots, \sigma_r u_r] $$
```
However, for larger multi-line equations, a normal workflow is to put it inside a LaTeX source block, e.g.

```
#+BEGIN_LaTeX   
\begin{equation} 
A[v_1, v_2, \ldots, v_r] = [\sigma_1 u_1, \sigma_2 u_2, \ldots, \sigma_r u_r]
\end{equation}
#+END_LaTeX
```

This does not export work with jekyll-org.  Are there any places in the codebase that this could be added?  Would you recommend I look at org-ruby?

**Comment by eggcaker** [comment]
use 
```
#+begin_src latex 
latex code here 
#+end_src

istea `begin_latex `
