### ISSUE TITLE
Warnings while starting jekyll server

### ISSUE THREAD

**Issue by k0va1** [eggcaker/jekyll-org#43]
I've added gem to Gemfile in group `:jekyll_plugins`. Everything works but why these warnings appears?

`/Users/a.koval/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-org-1.0.2/lib/jekyll-org.rb:37: warning: already initialized constant Jekyll::Document::DATELESS_FILENAME_MATCHER
/Users/a.koval/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/document.rb:14: warning: previous definition of DATELESS_FILENAME_MATCHER was here
/Users/a.koval/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-org-1.0.2/lib/jekyll-org.rb:38: warning: already initialized constant Jekyll::Document::DATE_FILENAME_MATCHER
/Users/a.koval/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/document.rb:15: warning: previous definition of DATE_FILENAME_MATCHER was here
Configuration file: /Users/a.koval/dev/kova1.gitlab.io/_config.yml
            Source: /Users/a.koval/dev/kova1.gitlab.io
       Destination: /Users/a.koval/dev/kova1.gitlab.io/_site
 Incremental build: disabled. Enable with --incremental`

**Comment by MoHKale** [comment]
I believe this was because an earlier version of this gem was redefining a lot of the Document class for the sake of simplicity. It should no longer be an issue, please check.
