### ISSUE TITLE
Change "_word_" to generic span "underline" rather than in-line text-decoration.

### ISSUE THREAD

**Issue by mashdot** [eggcaker/jekyll-org#7]
I just spotted than when I use:

`_word_`

It is parsed to:

`<span style="text-decoration:underline;">word</span>`

I am wanting to use underline as a means to highlight text in a document. Unfortunately [`<mark>` is not supported in org-mode](http://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00106.html), and so I would like to request the following output:

`<span class="underline">word</span>`

This would allow us to define and manage `underline` in CSS directly.

Thoughts?

**Comment by mashdot** [comment]
Thanks, sorry was on holiday so only caught up with this now. 

Opened issue: https://github.com/bdewey/org-ruby/issues/64

**Comment by mashdot** [comment]
Looks like I might have to jig `convert.rb` to allow for custom markup file: 

```
# Renders HTML with custom markup
Orgmode::Parser.new("* *Custom* /Markup/", { markup_file: "html.tags.yml" }).to_html
# => "<h1><strong>Custom</strong> <em>Markup</em></h1>\n"
```

```
---
:Tags:
  "_":  
    :open: span class=\"underline\"
    :close: span
```

See: https://github.com/wallyqs/org-ruby

**Comment by mashdot** [comment]
Sorry to open this again, but wondered if you could possibly include the `markup_file:` amendment by default? *Hopefully not failing if the `html.tags.yml` doesn't exist.*

Simply so that when someone who has amended it (like me), doesn't lose the change if they were ever to pull down an update. 

`org_text = Orgmode::Parser.new(content)`

to

`org_text = Orgmode::Parser.new(content,  { markup_file: "html.tags.yml" })`

Opened issue: https://github.com/wallyqs/org-ruby/issues/29

**Comment by eggcaker** [comment]
changed, please test if it works, thanks !
https://github.com/eggcaker/jekyll-org/blob/master/convert.rb#L43

**Comment by mashdot** [comment]
Superb! All good, many thanks again.
