### ISSUE TITLE
关于中文乱码问题

### ISSUE THREAD

**Issue by gttiankai** [eggcaker/jekyll-org#9]
你好:
       我使用的你的jekyll-org,来使用org-mode 配合 jekyll使用,但是我碰到了中文乱码问题,请问,怎么解决这个问题(ps:关于使用org-mode 来配合 jekyll的方式,我找了好久了,现在终于看到一个靠谱的,请千万帮忙)

**Comment by eggcaker** [comment]
我回头试试 以前好像没有发现过 你的中文是UTF8吗？还是GBK？

**Comment by gttiankai** [comment]
emacs version: 24.4.1

打开一个中英文混合编写的org 文件.
我使用alt + x ,然后执行 describe-coding-system:
Coding system for saving this buffer:
  Not set locally, use the default.
Default coding system (for new files):
  nil
Coding system for keyboard input:
  = -- no-conversion (alias: binary)

Coding system for terminal output:
  nil
Coding system for inter-client cut and paste:
  nil
Defaults for subprocess I/O:
  decoding: U -- utf-8-unix (alias: mule-utf-8-unix)
  encoding: U -- utf-8-unix (alias: mule-utf-8-unix)

**Comment by eggcaker** [comment]
hi @gttiankai , 
我刚才试了试，似乎没有发现什么问题。 我建了一个repo：https://github.com/eggcaker/jekyll-test ，你可以下载，试试。 有问题再打开issue. :+1:
